on:
  push:
    branches:
      - main
  
permissions:
  contents: write
  pull-requests: write
  issues: write
  
name: release-please
  
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.version }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  publish:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - env:
          tag: ${{ needs.release-please.outputs.version }}
        run: |
          echo "Version: $tag"
          echo "Tag name: $name"
          echo "Paths released: $paths_released"

      - name: Build and publish
        uses: macbre/push-to-ghcr@v15
        with:
          image_name: snakemake/snakemake-image-kubeflow
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ needs.release-please.outputs.version }}
