name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --tag snakemake/snakemake-image-kubeflow
      - name: Run tests
        run: |
          for cmd in "echo ~" # "snakemake --version" "which setup-wizard" "ls -l /home/jovyan/.local/bin"
          do
            docker run --user 1000 --rm snakemake/snakemake-image-kubeflow bash -c "source /home/jovyan/.bashrc; echo '$USER'; $cmd"
          done
