name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --tag snakemake/snakemake-image-kubeflow
      - name: Run tests
        # The source and the chmod are needed because github actions seems to do some
        # suprising things to the container when running it, which don't happen when
        # running it locally. This is a workaround to make the tests pass.
        run: |
          for cmd in "snakemake --version" "which setup-wizard"
          do
            docker run --user 1000 --rm snakemake/snakemake-image-kubeflow bash -c "source /home/jovyan/.bashrc; chmod +x ~/.local/bin/*; $cmd"
          done
